test:
	go test ./...
test-Login:
	go test -v -run Test_AdminAuthenticate ./... 
test-getCustomerByMobile:
	go test -v -run Test_GetCustomerByMobile ./... 
test-getCustomerByCode:
	go test -v -run Test_GetCustomerByBusinessCode ./... 

.PHONY: test test-login test-getCustomerByMobile test-getCustomerByCode